using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoTaggr.Data.Sqlite.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class InsertCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            const string sql = @"
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Afghanistan', 'AFG', 'AF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Albania', 'ALB', 'AL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Algeria', 'DZA', 'DZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('American Samoa', 'ASM', 'AS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Andorra', 'AND', 'AD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Angola', 'AGO', 'AO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Anguilla', 'AIA', 'AI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Antarctica', 'ATA', 'AQ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Antigua and Barbuda', 'ATG', 'AG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Argentina', 'ARG', 'AR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Armenia', 'ARM', 'AM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Aruba', 'ABW', 'AW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Australia', 'AUS', 'AU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Austria', 'AUT', 'AT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Azerbaijan', 'AZE', 'AZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bahamas (the)', 'BHS', 'BS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bahrain', 'BHR', 'BH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bangladesh', 'BGD', 'BD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Barbados', 'BRB', 'BB');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Belarus', 'BLR', 'BY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Belgium', 'BEL', 'BE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Belize', 'BLZ', 'BZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Benin', 'BEN', 'BJ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bermuda', 'BMU', 'BM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bhutan', 'BTN', 'BT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bolivia', 'BOL', 'BO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bonaire, Sint Eustatius and Saba', 'BES', 'BQ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bosnia and Herzegovina', 'BIH', 'BA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Botswana', 'BWA', 'BW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bouvet Island', 'BVT', 'BV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Brazil', 'BRA', 'BR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('British Indian Ocean Territory (the)', 'IOT', 'IO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Brunei Darussalam', 'BRN', 'BN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Bulgaria', 'BGR', 'BG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Burkina Faso', 'BFA', 'BF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Burundi', 'BDI', 'BI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cabo Verde', 'CPV', 'CV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cambodia', 'KHM', 'KH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cameroon', 'CMR', 'CM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Canada', 'CAN', 'CA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cayman Islands (the)', 'CYM', 'KY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Central African Republic (the)', 'CAF', 'CF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Chad', 'TCD', 'TD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Chile', 'CHL', 'CL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('China', 'CHN', 'CN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Christmas Island', 'CXR', 'CX');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cocos (Keeling) Islands (the)', 'CCK', 'CC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Colombia', 'COL', 'CO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Comoros (the)', 'COM', 'KM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Congo (the Democratic Republic of the)', 'COD', 'CD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Congo (the)', 'COG', 'CG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cook Islands (the)', 'COK', 'CK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Costa Rica', 'CRI', 'CR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Croatia', 'HRV', 'HR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cuba', 'CUB', 'CU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Curaçao', 'CUW', 'CW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Cyprus', 'CYP', 'CY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Czechia', 'CZE', 'CZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Côte d''Ivoire', 'CIV', 'CI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Denmark', 'DNK', 'DK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Djibouti', 'DJI', 'DJ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Dominica', 'DMA', 'DM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Dominican Republic (the)', 'DOM', 'DO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Ecuador', 'ECU', 'EC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Egypt', 'EGY', 'EG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('El Salvador', 'SLV', 'SV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Equatorial Guinea', 'GNQ', 'GQ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Eritrea', 'ERI', 'ER');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Estonia', 'EST', 'EE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Eswatini', 'SWZ', 'SZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Ethiopia', 'ETH', 'ET');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Falkland Islands (the) [Malvinas]', 'FLK', 'FK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Faroe Islands (the)', 'FRO', 'FO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Fiji', 'FJI', 'FJ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Finland', 'FIN', 'FI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('France', 'FRA', 'FR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('French Guiana', 'GUF', 'GF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('French Polynesia', 'PYF', 'PF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('French Southern Territories (the)', 'ATF', 'TF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Gabon', 'GAB', 'GA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Gambia (the)', 'GMB', 'GM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Georgia', 'GEO', 'GE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Germany', 'DEU', 'DE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Ghana', 'GHA', 'GH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Gibraltar', 'GIB', 'GI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Greece', 'GRC', 'GR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Greenland', 'GRL', 'GL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Grenada', 'GRD', 'GD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guadeloupe', 'GLP', 'GP');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guam', 'GUM', 'GU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guatemala', 'GTM', 'GT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guernsey', 'GGY', 'GG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guinea', 'GIN', 'GN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guinea-Bissau', 'GNB', 'GW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Guyana', 'GUY', 'GY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Haiti', 'HTI', 'HT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Heard Island and McDonald Islands', 'HMD', 'HM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Holy See (the)', 'VAT', 'VA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Honduras', 'HND', 'HN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Hong Kong', 'HKG', 'HK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Hungary', 'HUN', 'HU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Iceland', 'ISL', 'IS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('India', 'IND', 'IN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Indonesia', 'IDN', 'ID');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Iran (Islamic Republic of)', 'IRN', 'IR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Iraq', 'IRQ', 'IQ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Ireland', 'IRL', 'IE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Isle of Man', 'IMN', 'IM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Israel', 'ISR', 'IL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Italy', 'ITA', 'IT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Jamaica', 'JAM', 'JM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Japan', 'JPN', 'JP');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Jersey', 'JEY', 'JE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Jordan', 'JOR', 'JO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Kazakhstan', 'KAZ', 'KZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Kenya', 'KEN', 'KE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Kiribati', 'KIR', 'KI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Korea (the Democratic People''s Republic of)', 'PRK', 'KP');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('South Korea', 'KOR', 'KR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Kuwait', 'KWT', 'KW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Kyrgyzstan', 'KGZ', 'KG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Laos', 'LAO', 'LA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Latvia', 'LVA', 'LV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Lebanon', 'LBN', 'LB');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Lesotho', 'LSO', 'LS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Liberia', 'LBR', 'LR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Libya', 'LBY', 'LY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Liechtenstein', 'LIE', 'LI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Lithuania', 'LTU', 'LT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Luxembourg', 'LUX', 'LU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Macao', 'MAC', 'MO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Madagascar', 'MDG', 'MG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Malawi', 'MWI', 'MW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Malaysia', 'MYS', 'MY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Maldives', 'MDV', 'MV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mali', 'MLI', 'ML');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Malta', 'MLT', 'MT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Marshall Islands (the)', 'MHL', 'MH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Martinique', 'MTQ', 'MQ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mauritania', 'MRT', 'MR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mauritius', 'MUS', 'MU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mayotte', 'MYT', 'YT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mexico', 'MEX', 'MX');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Micronesia (Federated States of)', 'FSM', 'FM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Moldova (the Republic of)', 'MDA', 'MD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Monaco', 'MCO', 'MC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mongolia', 'MNG', 'MN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Montenegro', 'MNE', 'ME');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Montserrat', 'MSR', 'MS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Morocco', 'MAR', 'MA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Mozambique', 'MOZ', 'MZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Myanmar', 'MMR', 'MM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Namibia', 'NAM', 'NA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Nauru', 'NRU', 'NR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Nepal', 'NPL', 'NP');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Netherlands', 'NLD', 'NL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('New Caledonia', 'NCL', 'NC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('New Zealand', 'NZL', 'NZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Nicaragua', 'NIC', 'NI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Niger (the)', 'NER', 'NE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Nigeria', 'NGA', 'NG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Niue', 'NIU', 'NU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Norfolk Island', 'NFK', 'NF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Northern Mariana Islands (the)', 'MNP', 'MP');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Norway', 'NOR', 'NO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Oman', 'OMN', 'OM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Pakistan', 'PAK', 'PK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Palau', 'PLW', 'PW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Palestine, State of', 'PSE', 'PS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Panama', 'PAN', 'PA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Papua New Guinea', 'PNG', 'PG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Paraguay', 'PRY', 'PY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Peru', 'PER', 'PE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Philippines', 'PHL', 'PH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Pitcairn', 'PCN', 'PN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Poland', 'POL', 'PL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Portugal', 'PRT', 'PT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Puerto Rico', 'PRI', 'PR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Qatar', 'QAT', 'QA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('North Macedonia', 'MKD', 'MK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Romania', 'ROU', 'RO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Russia', 'RUS', 'RU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Rwanda', 'RWA', 'RW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Réunion', 'REU', 'RE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Barthélemy', 'BLM', 'BL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'SH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Kitts and Nevis', 'KNA', 'KN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Lucia', 'LCA', 'LC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Martin (French part)', 'MAF', 'MF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Pierre and Miquelon', 'SPM', 'PM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saint Vincent and the Grenadines', 'VCT', 'VC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Samoa', 'WSM', 'WS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('San Marino', 'SMR', 'SM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sao Tome and Principe', 'STP', 'ST');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Saudi Arabia', 'SAU', 'SA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Senegal', 'SEN', 'SN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Serbia', 'SRB', 'RS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Seychelles', 'SYC', 'SC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sierra Leone', 'SLE', 'SL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Singapore', 'SGP', 'SG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sint Maarten (Dutch part)', 'SXM', 'SX');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Slovakia', 'SVK', 'SK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Slovenia', 'SVN', 'SI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Solomon Islands', 'SLB', 'SB');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Somalia', 'SOM', 'SO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('South Africa', 'ZAF', 'ZA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('South Georgia and the South Sandwich Islands', 'SGS', 'GS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('South Sudan', 'SSD', 'SS');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Spain', 'ESP', 'ES');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sri Lanka', 'LKA', 'LK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sudan (the)', 'SDN', 'SD');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Suriname', 'SUR', 'SR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Svalbard and Jan Mayen', 'SJM', 'SJ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Sweden', 'SWE', 'SE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Switzerland', 'CHE', 'CH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Syrian Arab Republic', 'SYR', 'SY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Taiwan', 'TWN', 'TW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tajikistan', 'TJK', 'TJ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tanzania, United Republic of', 'TZA', 'TZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Thailand', 'THA', 'TH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Timor-Leste', 'TLS', 'TL');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Togo', 'TGO', 'TG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tokelau', 'TKL', 'TK');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tonga', 'TON', 'TO');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Trinidad and Tobago', 'TTO', 'TT');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tunisia', 'TUN', 'TN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Turkey', 'TUR', 'TR');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Turkmenistan', 'TKM', 'TM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Turks and Caicos Islands (the)', 'TCA', 'TC');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Tuvalu', 'TUV', 'TV');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Uganda', 'UGA', 'UG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Ukraine', 'UKR', 'UA');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('United Arab Emirates (the)', 'ARE', 'AE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('United Kingdom', 'GBR', 'GB');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('United States Minor Outlying Islands (the)', 'UMI', 'UM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('USA', 'USA', 'US');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Uruguay', 'URY', 'UY');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Uzbekistan', 'UZB', 'UZ');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Vanuatu', 'VUT', 'VU');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Venezuela', 'VEN', 'VE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Viet Nam', 'VNM', 'VN');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Virgin Islands (British)', 'VGB', 'VG');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Virgin Islands (U.S.)', 'VIR', 'VI');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Wallis and Futuna', 'WLF', 'WF');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Western Sahara', 'ESH', 'EH');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Yemen', 'YEM', 'YE');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Zambia', 'ZMB', 'ZM');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Zimbabwe', 'ZWE', 'ZW');
INSERT INTO Countries (Name, IsoCode3, IsoCode2) VALUES ('Åland Islands', 'ALA', 'AX');

";
            migrationBuilder.Sql(sql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
